# Generated by Django 6.0.2 on 2026-02-19 03:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'annonce", max_length=200, verbose_name='Titre')),
                ('description', models.TextField(help_text='Description détaillée', verbose_name='Description')),
                ('adresse', models.CharField(max_length=300, verbose_name='Adresse complète')),
                ('ville', models.CharField(default='Paris', max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(default='75000', max_length=10, verbose_name='Code postal')),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Loyer mensuel (€)')),
                ('caution', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caution (€)')),
                ('surface', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Surface (m²)')),
                ('nb_pieces', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de pièces')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='appartements/', verbose_name='Photo principale')),
                ('nb_vues', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('nb_favoris', models.IntegerField(default=0, verbose_name='Nombre de favoris')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Appartement',
                'verbose_name_plural': 'Appartements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('LOCATAIRE', 'Locataire'), ('PROPRIETAIRE', 'Propriétaire'), ('ADMIN', 'Administrateur')], default='LOCATAIRE', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]+$', 'Format téléphone invalide')], verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('verifie', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('notifications_email', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='location_user_set', related_query_name='location_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='location_user_set', related_query_name='location_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget maximum')),
                ('ville_recherche', models.CharField(blank=True, max_length=100, verbose_name='Ville recherchée')),
                ('total_reservations', models.IntegerField(default=0)),
                ('total_depenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dépenses totales')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_locataire', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='appartements/photos/', verbose_name='Photo')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.appartement', verbose_name='Appartement')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='Numéro SIRET')),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('commission', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Commission (%)')),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('total_appartements', models.IntegerField(default=0)),
                ('total_reservations', models.IntegerField(default=0)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_proprietaire', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Propriétaire',
                'verbose_name_plural': 'Propriétaires',
            },
        ),
        migrations.AddField(
            model_name='appartement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appartements', to='api.proprietaire', verbose_name='Propriétaire'),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='api.appartement', verbose_name='Appartement')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='api.locataire', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('locataire', 'appartement')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_locataire', models.CharField(max_length=100, verbose_name='Nom du locataire')),
                ('email_locataire', models.EmailField(max_length=254, verbose_name='Email du locataire')),
                ('telephone_locataire', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('RESERVE', 'Réservé'), ('CONFIRME', 'Confirmé'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='RESERVE', max_length=20, verbose_name='Statut')),
                ('date_reservation', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Montant total')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Commission')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.appartement', verbose_name='Appartement')),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.locataire', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-date_reservation'],
                'indexes': [models.Index(fields=['statut'], name='api_locatio_statut_a87f49_idx'), models.Index(fields=['date_debut', 'date_fin'], name='api_locatio_date_de_9cc177_idx'), models.Index(fields=['locataire'], name='api_locatio_locatai_7a2cf1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='appartement',
            index=models.Index(fields=['disponible'], name='api_apparte_disponi_1f4781_idx'),
        ),
        migrations.AddIndex(
            model_name='appartement',
            index=models.Index(fields=['ville'], name='api_apparte_ville_240794_idx'),
        ),
        migrations.AddIndex(
            model_name='appartement',
            index=models.Index(fields=['proprietaire'], name='api_apparte_proprie_9376ce_idx'),
        ),
    ]
