# Generated by Django 6.0.2 on 2026-02-27 01:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='caution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caution'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='loyer_mensuel',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Loyer mensuel (CFA)'),
        ),
    ]
