# Generated by Django 6.0.2 on 2026-03-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_premium_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='statut',
            field=models.CharField(choices=[('RESERVE', 'En attente de confirmation'), ('CONFIRME', 'Confirmé'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='RESERVE', max_length=20, verbose_name='Statut'),
        ),
    ]
