# Generated by Django 6.0.2 on 2026-02-27 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appartement_caution_and_more'),
        ('api', '0004_make_slug_unique'),
    ]

    operations = [
    ]
