# Generated by Django - Add DossierLocataire model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appartement_type_bien'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierLocataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('piece_identite', models.FileField(upload_to='dossiers_locataires/', verbose_name='Pièce d\'identité')),
                ('garant_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du garant')),
                ('garant_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du garant')),
                ('garant_telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du garant')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='api.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Dossier Locataire',
                'verbose_name_plural': 'Dossiers Locataires',
                'ordering': ['-date_creation'],
            },
        ),
    ]
