# Generated by Django 6.0.2 on 2026-03-09 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dossier_locataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='bien',
            field=models.ForeignKey(blank=True, help_text='Lien avec le bien dans le système Premium de comptabilité', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appartements', to='api.premiumbien', verbose_name='Bien Premium associé'),
        ),
    ]
