# Generated by Django 6.0.2 on 2026-04-01 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_email_register_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailloginotp',
            new_name='api_emaillo_email_82205b_idx',
            old_name='api_emaillo_email_6f5a9e_idx',
        ),
        migrations.RenameIndex(
            model_name='emailloginotp',
            new_name='api_emaillo_expires_13a81a_idx',
            old_name='api_emaillo_expires_88011d_idx',
        ),
        migrations.RenameIndex(
            model_name='emailregisterotp',
            new_name='api_emailre_email_816335_idx',
            old_name='api_emailre_email_978f59_idx',
        ),
        migrations.RenameIndex(
            model_name='emailregisterotp',
            new_name='api_emailre_expires_1fcf18_idx',
            old_name='api_emailre_expires_a47d4e_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
