"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from decouple import config
from datetime import timedelta
from urllib.parse import parse_qs, unquote, urlparse


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    'api',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Enable an easy development fallback to SQLite. By default we enable SQLite when
# DEBUG=True (so you don't need to have a working remote Postgres during dev).
# Set USE_SQLITE=False in your environment to force PostgreSQL even in DEBUG mode.
USE_SQLITE = config('USE_SQLITE', default=DEBUG, cast=bool)
USE_TRANSACTION_POOLER = config('USE_TRANSACTION_POOLER', default=True, cast=bool)
TRANSACTION_POOLER_URL = config(
    'SUPABASE_TRANSACTION_POOLER_URL',
    default=config('DATABASE_URL', default='')
)

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    db_config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='postgres'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default='6543'),
    }

    if USE_TRANSACTION_POOLER and TRANSACTION_POOLER_URL:
        parsed_db_url = urlparse(TRANSACTION_POOLER_URL)
        query_params = parse_qs(parsed_db_url.query)
        sslmode = query_params.get('sslmode', [None])[0] or config('DB_SSLMODE', default='require')

        db_config.update({
            'NAME': parsed_db_url.path.lstrip('/') or db_config['NAME'],
            'USER': unquote(parsed_db_url.username or db_config['USER']),
            'PASSWORD': unquote(parsed_db_url.password or db_config['PASSWORD']),
            'HOST': parsed_db_url.hostname or db_config['HOST'],
            'PORT': str(parsed_db_url.port or db_config['PORT']),
            'OPTIONS': {
                'sslmode': sslmode,
                'connect_timeout': config('DB_CONNECT_TIMEOUT', default=10, cast=int),
            },
            # Transaction poolers should not keep long-lived backend connections.
            'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=0, cast=int),
        })

        # Required with transaction pooling to avoid server-side cursor issues.
        DISABLE_SERVER_SIDE_CURSORS = config('DISABLE_SERVER_SIDE_CURSORS', default=True, cast=bool)

    DATABASES = {'default': db_config}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS Configuration
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='').split(',')
CORS_ALLOW_CREDENTIALS = True

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.SupabaseAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.StandardResultsSetPagination',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'API Gestion Location Appartements',
    'DESCRIPTION': "API REST pour la gestion de locations d'appartements",
    'VERSION': 'v1',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Configuration Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Utilisation d'un modèle utilisateur personnalisé
AUTH_USER_MODEL = 'api.User'

AUTHENTICATION_BACKENDS = [
    'api.auth_backends.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Supabase Configuration
SUPABASE_URL = config('SUPABASE_URL', default='https://gabwjrfyzctcsnmgezuv.supabase.co')
SUPABASE_JWT_SECRET = config('SUPABASE_JWT_SECRET', default='')
SUPABASE_JWT_ALGORITHMS = config('SUPABASE_JWT_ALGORITHMS', default='ES256,HS256')
SUPABASE_JWT_ISSUER = config('SUPABASE_JWT_ISSUER', default=f'{SUPABASE_URL}/auth/v1')

# Email (SMTP)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='api.email_backend.ConfigurableTLSEmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=30, cast=int)
EMAIL_TLS_VALIDATE_CERTS = config('EMAIL_TLS_VALIDATE_CERTS', default=True, cast=bool)
EMAIL_CA_FILE = config('EMAIL_CA_FILE', default='')

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'noreply@residance.local')
DOCUMENT_REPLY_TO_EMAIL = config('DOCUMENT_REPLY_TO_EMAIL', default=DEFAULT_FROM_EMAIL)